# configuration related to pull request comments
# to remove the comment, use:
comment: false
# comment:
#   behaviour: new # when posting a new report, remove the old one instead of updating it
#   require_changes: true # only post messages if the coverage changes

coverage:
  range: 50..90 # coverage lower than 50 is red, higher than 90 green, between color code

status:
  project:
    default:
      target: auto
      threshold: 5%
