# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: oldrel
      r_check_args: --no-build-vignettes --no-codoc --no-examples --ignore-vignettes
    - os: osx
      r: release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --ignore-vignettes

