(TeX-add-style-hook "mombf"
 (lambda ()
    (LaTeX-add-bibliographies
     "references")
    (LaTeX-add-environments
     "theorem"
     "lemma"
     "proposition"
     "corollary"
     "proof"
     "definition"
     "example"
     "remark")
    (LaTeX-add-labels
     "sec:priors"
     "ssec:prodpriors"
     "eq:pMOM"
     "ssec:quadpriors"
     "ssec:momprior"
     "multimoment"
     "ssec:imomprior"
     "eq:napd"
     "fig:priorplot"
     "fig:cdfplot"
     "sec:bflm"
     "ssec:lmfitandprior"
     "fig:priorhald"
     "ssec:bflmcomput"
     "fig:"
     "sec:bfglm"
     "sec:varsellm")
    (TeX-add-symbols
     "qed")
    (TeX-run-style-hooks
     "lscape"
     "epsf"
     "natbib"
     "hyperref"
     "verbatim"
     "graphicx"
     "bm"
     "amssymb"
     "amsmath"
     "Sweave"
     "latex2e"
     "art12"
     "article"
     "a4paper"
     "12pt")))

