# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

modelSelectionGGMC <- function(y, prCoef, prModel, samplerPars, Omegaini) {
    .Call(`_mombf_modelSelectionGGMC`, y, prCoef, prModel, samplerPars, Omegaini)
}

GGM_Gibbs_parallelC <- function(y, prCoef, prModel, samplerPars, Omegaini) {
    .Call(`_mombf_GGM_Gibbs_parallelC`, y, prCoef, prModel, samplerPars, Omegaini)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_mombf_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_mombf_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_mombf_rcpparma_bothproducts`, x)
}

